Repository FromDoppler/emms23, pull requests merged in 2023-09, with the labels that each got.

#164 DS-4728_change_navbar_items
  index.php
  registrado.php
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#165 DS-4796-Registered-DT-layout
  src/1.0.0/css/components/hero-registration.css
  src/img/icons/icon-arrow--white.svg
  stages/digital-trends/pre/digital-trends-registrado.php
Labels: size/M

#166 DS-4796-Registered-DT-layout-v2
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/pages/digital-trends.css
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/L

#167 DS-4786_sponsors_list
  config.php
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/L

#168 DS-4814-Add-form-fields
  ediciones-anteriores.php
  services/register.php
  sponsors.php
  src/1.0.0/css/components/intelInput.css
  src/1.0.0/css/components/register-modal.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/popUp.js
  src/1.0.0/js/vendors/intlTelInput.min.js
  src/1.0.0/js/vendors/utils.js
  src/components/head.php
  src/img/flags/flags.png
  src/img/flags/flags@2x.png
  stages/digital-trends/pre/digital-trends.php
  stages/ecommerce/post/ecommerce.php
  utils/DB.php
  utils/Doppler.php
  utils/SpreadSheetGoogle.php
Labels: size/XXL

#169 DS-4814_add_news_fields
  ediciones-anteriores.php
  services/register.php
  sponsors.php
  src/1.0.0/js/common/submitForm.js
  src/components/intellInput.php
  stages/digital-trends/pre/digital-trends.php
  stages/ecommerce/post/ecommerce.php
  utils/DB.php
  utils/Doppler.php
Labels: size/L

#170 DS-4747-Update-content
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/speakers-vip.css
  src/1.0.0/css/pages/digital-trends.css
  src/components/speakers.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/XL

#172 DS-4747-Update-content-v2
  ediciones-anteriores.php
  sponsors.php
  src/1.0.0/css/pages/digital-trends.css
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
  stages/ecommerce/post/ecommerce.php
Labels: size/L

#173 DS-4831_auto_set_flag_by_ip
  src/1.0.0/js/phoneFlag.js
  src/components/intellInput.php
Labels: size/S

#174 DS-4832-Flow-changes
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/speakers-vip.css
  src/components/speakers.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
Labels: size/M

#175 DS-4747-Update-content-v3
  ediciones-anteriores.php
  sponsors.php
  src/1.0.0/css/components/speakers-vip.css
  src/components/speakers.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
  stages/ecommerce/post/ecommerce.php
Labels: size/L

#176 DS-4827-Navbar-changes
  index.php
  registrado.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/XS

#177 DS-4747-Update-content-v4
  src/components/speakers.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#180 DS-4840-Speakers-vip
  src/1.0.0/css/components/speakers-vip.css
  src/components/speakers.php
Labels: size/XXL

#181 DS-4826_update_emails
  relay-confirmation-email/dt-earlybirds-wix/conferencias.png
  relay-confirmation-email/dt-earlybirds-wix/dt-earlybirds-wix.html
  relay-confirmation-email/dt-earlybirds-wix/networking2.png
  relay-confirmation-email/dt-earlybirds-wix/recursos.png
  relay-confirmation-email/dt-earlybirds-wix/ticket.png
  relay-confirmation-email/dt-earlybirds-wix/workshop2.png
  relay-confirmation-email/pre-dt/conferencias.png
  relay-confirmation-email/pre-dt/logo-emms-dt.png
  relay-confirmation-email/pre-dt/networking2.png
  relay-confirmation-email/pre-dt/ok-message.png
  relay-confirmation-email/pre-dt/pre-dt.html
  relay-confirmation-email/pre-dt/recursos.png
  relay-confirmation-email/pre-dt/ticket.png
  relay-confirmation-email/pre-dt/workshop2.png
  relay-confirmation-email/resumen-entrada-individual/resumen-entrada-individual.html
  relay-confirmation-email/resumen-entrada-pack/resumen-entrada-pack.html
Labels: size/XXL
