Repository FromDoppler/emms23, pull requests merged in 2023-12, with the labels that each got.

#277 DS-4961_refactoring_relay
  utils/Relay.php
  utils/relay-templates/dt/dt-during-template.html
  utils/relay-templates/dt/dt-earybirds-template.html
  utils/relay-templates/dt/dt-oldtemplate.html
  utils/relay-templates/dt/dt-post-template.html
  utils/relay-templates/dt/dt-pre-template.html
  utils/relay-templates/ecommerce/ecommerce-during-template.html
  utils/relay-templates/ecommerce/ecommerce-post-template.html
  utils/relay-templates/ecommerce/ecommerce-pre-template.html
  utils/relay-templates/wix/wix-empresa-template.html
  utils/relay-templates/wix/wix-invitado-template.html
  utils/relay-templates/wix/wix-vip-template.html
Labels: size/XXL

#279 DS-4972 fix catch error on subscription doppler list
  utils/subscriptionErrors.php
Labels: size/XS

#280 DS-4973-Add-sponsor-capsule
  sponsors-registrado.php
  sponsors.php
  src/img/conferences/portada-juancruz-arocena.png
Labels: size/S

#281 /DS-4975-Sponsors-alignment
  src/1.0.0/css/pages/sponsors.css
Labels: size/XS

#282 DS-4981-General-changes
  index.php
  registrado.php
  src/1.0.0/css/components/hero-registration.css
  stages/digital-trends/post/digital-trends.php
Labels: size/S

#283 DS-4981-General-changes-v2
  stages/digital-trends/post/digital-trends.php
Labels: size/XS
