Repository FromDoppler/emms23, pull requests merged in 2023-08, with the labels that each got.

#150 DS-4729-Prices-plans-module
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/styles.css
  src/1.0.0/js/collapsibles.js
  src/img/icons/icon-arrow--green.svg
  src/img/icons/icon-check--violet.svg
  src/img/icons/icon-discount.svg
  src/img/icons/icon-wrong.svg
  stages/digital-trends/pre/digital-trends.php
Labels: size/XL

#152 DS-4730_pop_up_register
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/js/popUp.js
  stages/digital-trends/pre/digital-trends.php
Labels: size/L

#153 DS-4752-Change-october-to-november
  index.php
  registrado.php
  src/1.0.0/css/components/event-cards.css
  stages/ecommerce/post/ecommerce-registrado.php
Labels: size/M

#154 DS-4730_fix_button_popUp
  src/1.0.0/css/components/prices-plans.css
  stages/digital-trends/pre/digital-trends.php
Labels: size/XS

#155 DS-4768_collapsible_question_bug
  src/1.0.0/js/collapsibles.js
Labels: size/M

#156 DS-4729-Price-module-corrections
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/pages/digital-trends.css
  stages/digital-trends/pre/digital-trends.php
Labels: size/S

#151 DS-4726 API WIX
  .gitignore
  wix/readme
  wix/v1/api/controllers/SubscriberController.php
  wix/v1/api/models/SubscriberDatabase.php
  wix/v1/api/models/SubscriberDopplerList.php
  wix/v1/api/models/SubscriberWix.php
  wix/v1/api/save_subscriber_data.php
  wix/v1/api/utils/Logger.php
  wix/v1/api/utils/toHex.php
Labels: size/L

#157 DS-4772-Update-dt-email-content
  relay-confirmation-email/early-birds-digital-trends/early-birds-digital-trends.html
  utils/Relay.php
Labels: size/S

#158 DS-4767 wix api client
  .docker/docker-compose.yml
  config.php
  wix/v1/api/utils/WixApiClient.php
Labels: size/L

#159 DS-4671_check_endopints
  services/getDuringDays.php
  services/getSettingsTransmission.php
  services/getSimulator.php
  services/getSimulatorDuringDays.php
  services/setDuringDays.php
  services/setPhase.php
  services/setSimulator.php
  services/setSimulatorDuringDays.php
  services/setTransmission.php
  utils/DB.php
Labels: size/L

#160 DS-4772-Update-dt-email-content
  config.php
  utils/Relay.php
Labels: size/XS

#162 DS-4788_fix_forms
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/js/popUp.js
  stages/digital-trends/pre/digital-trends.php
Labels: size/L
