Repository FromDoppler/emms23, pull requests merged in 2023-11, with the labels that each got.

#238 DS-4908 fix cache name dt
  src/components/cacheSettings.php
Labels: size/XS

#239 DS-4873-During-files-revision-v3
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
Labels: size/XS

#241 DS-4875_fix_links
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends-registrado.php
Labels: size/S

#242 DS-4910-DT-Registered-hellobar
  src/1.0.0/css/components/header.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-registration.css
  stages/digital-trends/pre/digital-trends-registrado.php
Labels: size/M

#243 DS-4911_add_new_fields_in_spread
  utils/SpreadSheetGoogle.php
Labels: size/M

#245 DS-4891-Change-block-to-DT
  index.php
  registrado.php
Labels: size/S

#246 DS-4898_add_workshop_logic
  src/1.0.0/js/common/certificate.js
  textify/certificate-emms2023.php
  textify/certificate-emms2023qa.php
Labels: size/M

#247 DS-4913-DT-Post-files
  src/1.0.0/css/pages/digital-trends.css
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
  stages/ecommerce/post/ecommerce.php
Labels: size/XL

#248 DS-4914-Fix-DT-share
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/S

#249 DS-4889-New-sponsor-capsule
  sponsors-registrado.php
  sponsors.php
  src/img/conferences/portada-youtube-mundobrandes-min.png
Labels: size/S

#250 DS-4915-Fix-visual-home
  index.php
  registrado.php
  src/1.0.0/css/pages/home.css
Labels: size/S

#251 DS-4933_add_datejs
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#252 DS-4913-DT-Post-files-v2
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
Labels: size/XL

#253 DS-4932-Hide-free-plan-in-mobile
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends-registrado.php
Labels: size/XS

#255 DS-4926-During-content
  index.php
  registrado.php
  src/1.0.0/css/components/hero-conference.css
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
Labels: size/M

#257 DS-4603_dt_during_email
  relay-confirmation-email/during-dt/cinema.png
  relay-confirmation-email/during-dt/during-dt.html
  relay-confirmation-email/during-dt/logo-emms-dt.png
  relay-confirmation-email/during-dt/ok-message.png
  relay-confirmation-email/during-dt/separador.png
  relay-confirmation-email/during-dt/worlshops.gif
  utils/Relay.php
Labels: size/XXL

#258 fixes-meet-predeploy
  src/1.0.0/css/components/hero-conference.css
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/post/digital-trends.php
Labels: size/S

#260 DS-4603_fix_during_email_DT
  utils/Relay.php
Labels: size/XS

#259 DS-4920_DS-4921_DS-4923_DS-4924_workshop_security
  descarga-certificado.php
  src/1.0.0/js/certificate/certificateWorkshop.js
  src/1.0.0/js/common/certificate.js
Labels: size/L

#261 DS-4918-DS-4919 find_contact_by_email & update_contact_name
  wix/v1/api/controllers/WixContactController.php
  wix/v1/api/find_contact_by_email.php
  wix/v1/api/models/WixContactsDatabase.php
  wix/v1/api/update_contact_name.php
Labels: size/L

#262 DS-4922_add_spinner
  descarga-certificado.php
  src/1.0.0/css/scripts/certificate.css
  src/1.0.0/js/certificate/certificateWorkshop.js
  src/img/apple-touch-icon.png
  src/img/logoemms-nobg.png
Labels: size/M

#263 DS-4925-Update-post-content
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
Labels: size/S

#264 DS-4935_fix_dplrid
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/user.js
Labels: size/S

#265 DS-4936 fix date es
  src/1.0.0/js/date.js
Labels: size/XS

#267 DS-4938-Change-transition-banner-content
  stages/digital-trends/during/digital-trends-registrado.php
Labels: size/S

#266 DS-4934 fix blank screen on top
  src/1.0.0/js/commonAnimations.js
Labels: size/XS

#268 DS-4937-Add-new-capsules
  sponsors-registrado.php
  sponsors.php
  src/img/conferences/portada-natalia-tabares-min.png
  src/img/conferences/portada-youtube-cyberclick.png
  src/img/conferences/portada-youtube-lujanalonso-min.png
  src/img/conferences/portada-youtube-veronicasequeira-min.png
Labels: size/M

#269 DS-4604_dt_email_post
  relay-confirmation-email/post-dt/certificado.png
  relay-confirmation-email/post-dt/cinema.png
  relay-confirmation-email/post-dt/logo-emms-dt.png
  relay-confirmation-email/post-dt/post-dt.html
  relay-confirmation-email/post-dt/separador.png
  relay-confirmation-email/post-dt/tools.png
  relay-confirmation-email/post-dt/worlshops.gif
  utils/Relay.php
Labels: size/XXL

#270 DS-4937-Add-new-capsules-v2
  sponsors-registrado.php
  sponsors.php
  src/img/conferences/portada-mariafernanda-rangel-castillo-min.png
Labels: size/S

#271 DS-4925-Update-post-content-v2
  index.php
  registrado.php
  src/1.0.0/css/pages/home.css
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
Labels: size/M

#272 DS-4942_abstract_speaker_certificate
  speaker-interna.php
  src/1.0.0/js/certificate/certificateSpeaker.js
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
Labels: size/M

#273 DS-4925-Update-post-content-v3
  stages/digital-trends/post/digital-trends-registrado.php
  stages/digital-trends/post/digital-trends.php
  stages/ecommerce/post/ecommerce-registrado.php
Labels: size/M

#274 DS-4944-Fix-logos-marquee
  src/1.0.0/css/components/hero-registration.css
  stages/digital-trends/post/digital-trends.php
  stages/ecommerce/post/ecommerce.php
Labels: size/L

#275 DS-4937-Add-new-capsule
  sponsors-registrado.php
  sponsors.php
  src/img/conferences/portada-denborg-min.png
Labels: size/S

#276 DS-4945_delete_old_generator
  campaignGenerator/exampleTemplate.html
  campaignGenerator/maquetas-generadas/.gitkeep
  campaignGenerator/massiveCampaignGenerator.php
Labels: size/XXL
