Repository FromDoppler/emms23, pull requests merged in 2023-10, with the labels that each got.

#178 DS-4839_fix_intell_input
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/phoneFlag.js
  src/components/intellInput.php
Labels: size/M

#184 DS-4843-Fixes-DT
  src/components/speakers.php
  src/img/conferencias.png
  src/img/entrevistas.png
  src/img/exito.png
  src/img/networking.png
  src/img/recursos.png
  src/img/workshop.png
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#186 DS-4810-Edit-form-content
  ediciones-anteriores.php
  sponsors.php
Labels: size/XS

#183 DS-4826_fix_emails
  relay-confirmation-email/dt-earlybirds-wix/dt-earlybirds-wix.html
  relay-confirmation-email/resumen-entrada-individual/resumen-entrada-individual.html
  relay-confirmation-email/resumen-entrada-pack/resumen-entrada-pack.html
Labels: size/L

#185 DS-4844_fix_edit_speaker
  admin/speakers/edit_speakers.php
Labels: size/S

#187 DS-4811 wix api update flow
  .docker/config/nginx/default.conf
  .docker/config/php/php.conf.ini
  .docker/db/EMMS23.sql
  .docker/docker-compose.yml
  config.php
  wix/v1/api/controllers/SubscriberController.php
  wix/v1/api/models/SubscriberDatabase.php
  wix/v1/api/models/SubscriberWix.php
  wix/v1/api/models/WixContactsDatabase.php
  wix/v1/api/utils/Logger.php
  wix/v1/api/utils/SpreadSheetGoogle.php
  wix/v1/api/utils/WixApiClient.php
  wix/v1/api/utils/getCurrentPhase.php
  wix/v1/api/utils/sendEmail.php
Labels: size/XL

#189 DS-4834_add_wix_email_temapltes
  utils/Relay.php
Labels: size/XXL

#191 DS-4858_fix_userid
  src/1.0.0/js/user.js
Labels: size/S

#192 hot_fix_deplo_10042023
  services/register.php
  utils/SpreadSheetGoogle.php
Labels: size/XS

#194 hot_fix_deplo_10042023
  src/components/speakers.php
Labels: size/XS

#195 hot_fix_deplo_10042023
  src/components/speakers.php
Labels: size/S

#193 fix-speakers
  src/1.0.0/css/components/calendar.css
Labels: size/XS

#196 DS-4861-DT-Sponsors-integration
  config.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/S

#197 DS-4848_add_new_email_template
  relay-confirmation-email/pre-dt/cohete.png
  relay-confirmation-email/pre-dt/conferencias.png
  relay-confirmation-email/pre-dt/networking.png
  relay-confirmation-email/pre-dt/networking2.png
  relay-confirmation-email/pre-dt/ok-message.png
  relay-confirmation-email/pre-dt/pre-dt.html
  relay-confirmation-email/pre-dt/recursos.png
  relay-confirmation-email/pre-dt/separador.png
  relay-confirmation-email/pre-dt/ticket.png
  relay-confirmation-email/pre-dt/workshop.png
  relay-confirmation-email/pre-dt/workshop1.png
  relay-confirmation-email/pre-dt/workshop2.png
  relay-confirmation-email/pre-dt/workshop3.png
  relay-confirmation-email/pre-dt/workshop4.png
  relay-confirmation-email/pre-dt/workshop5.png
  src/1.0.0/js/user.js
  utils/Relay.php
Labels: size/XXL

#198 DS-4860_update_sitemap
  sitemap.xml
Labels: size/XS

#199 DS-4859-Fixes-post-deploy
  ediciones-anteriores.php
  sponsors.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/speakers-vip.css
  src/components/speakers.php
Labels: size/S

#200 DS-4829-Fix-capsules
  sponsors.php
  src/1.0.0/css/pages/sponsors.css
Labels: size/M

#201 DS-4863_fix_register
  services/register.php
Labels: size/S

#202 fix(speakers-vip): icon star size
  src/1.0.0/css/components/speakers-vip.css
Labels: size/XS

#203 DS-4855-Update-twitter-logo
  src/img/Twitter-w.svg
  src/img/icons/icono-twitter-b.svg
  src/img/icons/icono-twitter.svg
Labels: size/S

#204 DS-4661_add_event_filyer
  admin/speakers/index.php
Labels: size/S

#205 DS-4865-Sponsors-inactive-btn
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/pages/sponsors.css
Labels: size/S

#206 DS-4873-DT-During
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
Labels: size/XXL

#207 DS-4874-Fix-DT-no-logged
  stages/digital-trends/pre/digital-trends.php
Labels: size/L

#208 DS-4872_change_cacheSettings.php
  index.php
  registrado.php
  src/components/cacheSettings.php
Labels: size/L

#210 fix-sponsors-status
  utils/DB.php
Labels: size/XS

#211 fix: clear name
  wix/v1/api/models/SubscriberWix.php
Labels: size/XS

#212 DS-4877 add doble optin
  config.php
  services/register.php
  utils/Doppler.php
  wix/v1/api/controllers/SubscriberController.php
  wix/v1/api/models/SubscriberDopplerList.php
  wix/v1/api/utils/email-doble-optin.html
Labels: size/L

#214 DS-4879-Config-DT-Home-cards
  index.php
  registrado.php
Labels: size/M

#213 DS-4880_fix_events_form
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/user.js
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#215 fix: fix encode email register without form
  src/1.0.0/js/common/submitForm.js
Labels: size/XS

#216 fix undefined users
  src/1.0.0/js/user.js
Labels: size/XS

#217 clear undefined users
  src/1.0.0/js/global.js
  src/1.0.0/js/user.js
  src/components/footer.php
Labels: size/S

#218 fix convert event string to array localstorage
  src/1.0.0/js/global.js
  src/1.0.0/js/sponsors.js
Labels: size/S

#219 update-speaker-interna-form
  speaker-interna.php
Labels: size/M

#220 DS-4870_massive_campaing_generator
  campaignGenerator/exampleTemplate.html
  campaignGenerator/maquetas-generadas/.gitkeep
  campaignGenerator/massiveCampaignGenerator.php
Labels: size/XXL

#221 DS-4870_edit_template
  campaignGenerator/exampleTemplate.html
Labels: size/L

#222 DS-4884-DT-webflow-changes
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/speakers-vip.css
  src/1.0.0/css/general/constants.css
  src/components/speakers.php
  src/img/icons/icon-star-gradient--mirrored.png
  src/img/icons/icon-star-gradient--pair.png
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/XXL

#223 DS-4886 storage subscription doppler list errors
  .docker/db/EMMS23.sql
  .docker/db/queries/get_subscription_doppler_errors.sql
  services/register.php
  utils/DB.php
  utils/subscriptionErrors.php
  wix/v1/api/models/SubscriberDopplerList.php
Labels: size/M

#224 DS-4882-Download-certificate-template
  descarga-certificado.php
  src/1.0.0/css/pages/certificate-download.css
  src/1.0.0/css/styles.css
Labels: size/L

#225 DS-4884-DT-webflow-changes-v2
  src/1.0.0/css/components/speakers-vip.css
  src/components/speakers.php
Labels: size/L

#227 DS-4903_fix_multiple_from
  src/1.0.0/js/popUp.js
  src/components/intellInput.php
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/M

#228 DS-4903_fix_multiple_from
  src/1.0.0/js/autoComplete.js
  src/components/footer.php
Labels: size/M

#226 DS-4867_fix_register
  services/register.php
  utils/DB.php
  utils/Validator.php
Labels: size/L

#229 DS-4905_fix_speaker_without_time
  src/1.0.0/js/date.js
  src/components/speakers.php
Labels: size/L

#230 DS-4888-Content-update
  src/1.0.0/css/components/event-numbers.css
  src/1.0.0/css/components/hero-registration.css
  src/components/speakers.php
  src/img/marquee/amazon.png
  src/img/marquee/google.png
  src/img/marquee/linkedin.png
  src/img/marquee/meta.png
  src/img/marquee/metricool.png
  src/img/marquee/microsoft.png
  src/img/marquee/spotify.png
  src/img/marquee/tiktok.png
  src/img/marquee/vtex.png
  src/img/marquee/youtube.png
  stages/digital-trends/pre/digital-trends-registrado.php
  stages/digital-trends/pre/digital-trends.php
Labels: size/L

#231 DS-4906_fix_newtworking_hour
  src/1.0.0/js/date.js
  src/components/speakers.php
Labels: size/L

#232 DS-4871-Visual-fixes
  index.php
  registrado.php
  src/1.0.0/css/components/speakers-vip.css
  src/img/networking.png
  src/img/workshop.png
Labels: size/M

#233 DS-4904_DS-4897_add_new_certificate
  descarga-certificado.php
  speaker-interna.php
  src/1.0.0/css/components/certificate-modal.css
  src/1.0.0/js/certificate/certificateDt.js
  src/1.0.0/js/certificate/certificateEcommerce.js
  src/1.0.0/js/certificate/certificateWorkshop.js
  src/1.0.0/js/common/certificate.js
  stages/digital-trends/during/digital-trends-registrado.php
  stages/ecommerce/during/ecommerce-registrado.php
Labels: size/L

#235 DS-4873-During-files-revision
  src/1.0.0/css/components/prices-plans.css
  stages/digital-trends/during/digital-trends-registrado.php
  stages/digital-trends/during/digital-trends.php
  stages/digital-trends/pre/digital-trends-registrado.php
Labels: size/L

#236 DS-4908 add dt cache current state
  src/components/cacheSettings.php
Labels: size/S

#237 DS-4873-During-files-revision-v2
  config.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/header.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/pages/digital-trends.css
  src/img/banner-migrate-twitch-DT.png
  src/img/banner-technical-error-DT.png
  stages/digital-trends/during/digital-trends-registrado.php
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
Labels: size/L
